// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace BattleDelts
{
public static class GPGSIds
{
        public const string achievement_sigma_chi_gym = "CgkI0dqc5bQeEAIQBg"; // <GPGSID>
        public const string achievement_member_catcher = "CgkI0dqc5bQeEAIQAg"; // <GPGSID>
        public const string leaderboard_highest_level = "CgkI0dqc5bQeEAIQCw"; // <GPGSID>
        public const string achievement_delta_sig_gym = "CgkI0dqc5bQeEAIQBw"; // <GPGSID>
        public const string achievement_recruitment_is_an_obligation = "CgkI0dqc5bQeEAIQBQ"; // <GPGSID>
        public const string leaderboard_gyms_defeated = "CgkI0dqc5bQeEAIQCg"; // <GPGSID>
        public const string leaderboard_battles_won = "CgkI0dqc5bQeEAIQDA"; // <GPGSID>
        public const string achievement_pledge_catcher = "CgkI0dqc5bQeEAIQAA"; // <GPGSID>
        public const string achievement_exec_catcher = "CgkI0dqc5bQeEAIQAw"; // <GPGSID>
        public const string leaderboard_time_played = "CgkI0dqc5bQeEAIQDg"; // <GPGSID>
        public const string leaderboard_deltdexes_collected = "CgkI0dqc5bQeEAIQCQ"; // <GPGSID>
        public const string achievement_composites = "CgkI0dqc5bQeEAIQBA"; // <GPGSID>
        public const string leaderboard_delts_rushed = "CgkI0dqc5bQeEAIQDQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkI0dqc5bQeEAIQEA"; // <GPGSID>
        public const string achievement_sigma_nu_gym = "CgkI0dqc5bQeEAIQCA"; // <GPGSID>
        public const string achievement_neophyte_catcher = "CgkI0dqc5bQeEAIQAQ"; // <GPGSID>

}
}
